### ISSUE TITLE
Definition des PersonBase-Elements falsch

### ISSUE THREAD

**Issue by s-stoffel** [OTDS-eV/OTDS#42]
Hallo,

ich habe versucht, aus den aktuellsten XSDs (1.9.3. b) per "xsd"-Tool C#-Klassen zur Deserialisierung von OTDS-Daten zu generieren. Dazu habe ich einmal die XSD aus dem OTDS-Forum und einmal hier aus dem "1.9.3-b"-Tag verwendet.
In beiden Fällen hat das xsd-Tool mir Fehler ausgespuckt, dasselbe gilt für die XSDs aus dem "1.9.3"-Tag. _Mit den XSDs aus dem "1.9.2"-Tag gab es jedoch keine Fehler_. Die Fehlermeldung sagte was von einer "circular group reference" bei der AllocationBaseGroup, aber das ist eigentlich irreführend, wie sich später herausstellte.

Nach einigem Suchen und Experimentieren ist mir dann aufgefallen, dass in der aktuellsten Version der XSDs die Definition des PersonBase-Elements anscheinend "kaputt gegangen" ist, so wie es aussieht bereits beim Sprung von Version 1.9.2 auf 1.9.3. Wenn ich die PersonBase-Defintion aus v1.9.2 in die aktuelle XSD rein kopiere (siehe Screenshot), dann klappt alles.

Grüße,
Simon

![grafik](https://user-images.githubusercontent.com/22023953/33014330-449e6582-cde7-11e7-96a7-84dd9e90865c.png)

**Comment by OTDSeV** [comment]
Hallo Simon,

vielen Dank für diesen Hinweis, da werden wir mal gleich einsteigen und das überprüfen!
Darf ich noch kurz fragen, wo Du arbeitest und in welchem Kontext Du Dich mit OTDS beschäftigst?

Danke nochmal und viele Grüße

Steffi Schweden
Leitung Geschäftsstelle

OTDS e.V.
Schicklerstraße 5-7
D-10179 Berlin
Tel:     +49 30 284 06-29
Mobil: +49 171 222 05 11
steffi.schweden@otds.de<mailto:steffi.schweden@otds.de>

http://www.otds.de<http://www.otds.de/>

[OTDS_Logo (380x64)]

Von: s-stoffel [mailto:notifications@github.com]
Gesendet: Montag, 20. November 2017 11:38
An: OTDS-eV/OTDS <OTDS@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [OTDS-eV/OTDS] Definition des PersonBase-Elements falsch (#42)


Hallo,

ich habe versucht, aus den aktuellsten XSDs (1.9.3. b) per "xsd"-Tool C#-Klassen zur Deserialisierung von OTDS-Daten zu generieren. Dazu habe ich einmal die XSD aus dem OTDS-Forum und einmal hier aus dem "1.9.3-b"-Tag verwendet.
In beiden Fällen hat das xsd-Tool mir Fehler ausgespuckt, dasselbe gilt für die XSDs aus dem "1.9.3"-Tag. Mit den XSDs aus dem "1.9.2"-Tag gab es jedoch keine Fehler. Die Fehlermeldung sagte was von einer "circular group reference" bei der AllocationBaseGroup, aber das ist eigentlich irreführend, wie sich später herausstellte.

Nach einigem Suchen und Experimentieren ist mir dann aufgefallen, dass in der aktuellsten Version der XSDs die Definition des PersonBase-Elements anscheinend "kaputt gegangen" ist, so wie es aussieht bereits beim Sprung von Version 1.9.2 auf 1.9.3. Wenn ich die PersonBase-Defintion aus v1.9.2 in die aktuelle XSD rein kopiere (siehe Screenshot), dann klappt alles.

Grüße,
Simon

[grafik]<https://user-images.githubusercontent.com/22023953/33014330-449e6582-cde7-11e7-96a7-84dd9e90865c.png>

**Comment by s-stoffel** [comment]
Gerne ;-) Ich bin bei der TravelTrex GmbH und soll im Rahmen eines aktuellen Projektes die OTDS-Daten eines Partners verarbeiten.

**Comment by OTDSeV** [comment]
Hallo Simon,
schön zu hören, dass TravelTrex (wieder/immernoch) mit OTDS arbeitet - wir hatten in der Vergangenheit schon Kontakt. 
Ich hatte gerade mal in unsere Datenbank der Leute geschaut, die sich über unsere Webseite für unser OTDS-Forum angemeldet haben. Dort legen wir die aktuellen XSD-Dateien sowie die Dokumentation für OTDS ab. Allerdings habe ich keinen User gefunden, der auf "Simon" oder "Traveltrex" hindeutet. Hast Du den Zugriff auf OTDS hier über Github realisiert? Falls ja, empfehle ich Dir, Dich auf www.otds.de für das Forum anzumelden - das ist natürlich kostenfrei und unverbindlich.
Außerdem hast Du meine Neugier weiter angefacht: habt Ihr mehrere Partner, die Euch OTDS liefern? Wenn ja, kannst Du Namen nennen? Wir vom Verein haben immer gern ein möglichst komplettes Bild davon, wer OTDS einsetzt, um unsere Argumentation zum immer weiter verbreiteten Datenstandard mit Fakten zu untermauern... 

Wegen des von Dir gemeldeten Problems melden wir uns in Kürze bei Dir!

Viele Grüße
Steffi

**Comment by OTDSeV** [comment]
Hallo Simon,
sorry für die Funkstille. Wir haben in der Zwischenzeit intensiv an der OTDS-Version 2.0 gearbeitet, die im letzten Prüfstadium ist. Das von Dir beschriebene Problem mit dem PersonBase Element haben wir bei der Gelegenheit auch gelöst, vielen Dank noch einmal für den Hinweis darauf. Mitte nächster Woche sollte die Version veröffentlicht sein, bitte achte einfach auf die News im OTDS-Forum oder auf unserer Webseite.
Wir würden uns freuen, wenn Du uns auch weiterhin mit Deinem Feedback unterstützt und mithilfst, OTDS noch besser zu machen.
Viele Grüße
Steffi
